README.md
RDKit installation instructions from `README.md` were incomplete, as the channel to find `rdkit` in was missing (thanks @sarahnlewis for noticing!). I'm adding the missing part of the command here.
=> Specify conda channel for rdkit

.github/workflows/ci.yml
Add 'worflow_dispatch' to the list of triggers in `ci.yml` so that the workflow can be triggered manually.
=> Allow CI to be manually triggered

.gitignore, CHANGELOG.md, setup.py
This PR sets up automatic versioning using `setuptools_scm` which reads the version from git's tags, so that there is no need to manually update `setup.py`. Once this is merged, I will tag the resulting commit with a `0.1.0` tag to mark the initial public release.
=> Set up versioning

molecule_generation/cli/encode.py, molecule_generation/cli/sample.py, molecule_generation/utils/moler_visualisation_utils.py
After some of the refactoring done in #6, `ModelWrapper` is now an abstract base class that cannot be instantiated. This broke the CLI entry points, which were all still using `ModelWrapper` (thanks Tien Huynh for flagging!).
This PR is a quick fix of simply replacing `ModelWrapper` with `VaeWrapper`, which is the concrete wrapper class for `MoLeRVae`. There are two extensions that I'd defer to follow-up PRs in order to fix CLI quicker:
- We should have tests covering CLI itself so that we don't break it in the future.
- Some CLI endpoints (e.g. `sample`) could support `MoLeRGenerator`, but they won't if we use `VaeWrapper` and not `GeneratorWrapper`.
=> Fix CLI by using VaeWrapper instead of ModelWrapper

CHANGELOG.md, setup.py
Recently a breaking version of `protobuf` was released, which broke many downstream libraries that didn't pin the version (see [this thread](https://github.com/protocolbuffers/protobuf/issues/10051)). Following these other libraries, in this PR I constrain the `protobuf` version to `<4`.
=> Constrain protobuf version to avoid a breaking release

CHANGELOG.md, molecule_generation/utils/moler_inference_server.py, molecule_generation/wrapper.py
When doing encoding in `MoLeRVae`, we currently only return the mean latent code, ignoring the variance. This is enough for many applications (e.g. optimization), but in certain cases knowing the entire distribution can be useful. In this PR, I add a flag that makes `encode` also return the variances.
=> Enable encoding to also return log variance

CHANGELOG.md, molecule_generation/layers/moler_decoder.py, molecule_generation/test/layers/test_moler_decoder.py, molecule_generation/utils/moler_decoding_utils.py, molecule_generation/utils/moler_visualisation_utils.py
This PR contains two high-level changes:
- The generation step info during MoLeR's decoding was passed around in a somewhat convoluted way, by keeping three lists containing steps of different types (atom addition, bond addition, attachment point selection), aligned such that for each index only one of the lists contained an actual class, while the other ones contained `None`. I refactored this so that there is a single list with step info classes, which reduced the amount of bookkeeping needed.
- Even though the step info classes collect all sorts of useful information, the partial molecules were not explicitly kept around, and they are needed for running post-hoc analysis. One complication here is that most of the step information is available early on, while the molecule is constructed …
=> Refactor and improve generation step tracking

CHANGELOG.md, README.md, molecule_generation/chem/molecule_dataset_utils.py, molecule_generation/cli/preprocess.py
As discussed in #21, fine-tuning models was not fully supported, as preprocessing data for fine-tuning would need to know about atom featurisers and motif vocabulary built during pretraining, and there was no way to plug those in. I add support for this here, and explain how to perform fine-tuning in `README.md`.
=> Add support for fine-tuning

README.md
As highlighted in #31, for some system versions installing tensorflow may not work out-of-the-box. This is not specific to `molecule_generation`, but it doesn't hurt to point to tensorflow's website in case such issues arise, so I'm adding a quick note in the README here.
=> Point to tensorflow website in case of installation issues

.github/workflows/ci.yml, CHANGELOG.md, README.md, environment.yml, molecule_generation/__init__.py, molecule_generation/layers/graph_property_predictor.py, molecule_generation/version.py, setup.py
This PR unpins the main dependencies, so that one can use various versions of Python and tensorflow. I quickly checked and things seem to work under modern versions, with the exception of one silly bug in CGVAE files that I had to fix. I also changed the CI buld so that it tests the code both under the old versions (to make sure they continue to work) and modern versions (Python 3.9, tf 2.9).
=> Support modern versions of Python and tensorflow

README.md
It turns out that figshare (which we use to provide the pretrained model checkpoint) doesn't work in China without a VPN. In this PR, I add a mirror link to the same checkpoint uploaded to Baidu Cloud (thanks @fiberleif!).
=> Add a mirror link for the pretrained checkpoint

.github/workflows/ci.yml, CHANGELOG.md, molecule_generation/chem/molecule_dataset_utils.py, molecule_generation/chem/motif_utils.py, molecule_generation/layers/moler_decoder.py, molecule_generation/models/cgvae.py, molecule_generation/models/moler_base_model.py, molecule_generation/models/moler_generator.py, molecule_generation/models/moler_vae.py, molecule_generation/utils/decoder_batching.py, molecule_generation/utils/epoch_metrics_logger.py, molecule_generation/utils/moler_inference_server.py, molecule_generation/utils/moler_visualisation_utils.py
A recent CI failure on #49 highlighted the fact that the new `black` version `23.*` introduces some formatting changes with respect to `22.*`. Since the changes are relatively minor, I apply them here, but also pin `black` in CI to avoid such unexpected CI failures in the future.
=> Reformat with `black==23.1.0` and pin its version in CI

CHANGELOG.md, README.md, molecule_generation/chem/valence_constraints.py, molecule_generation/test/utils/test_valence_constraints.py
In `numpy 1.24.0`, [some array types were deprecated](https://numpy.org/doc/stable/release/1.24.0-notes.html), including `np.bool` and `np.int` which appeared a few times in our code. This made `molecule_generation` no longer work with newest `numpy` (mentioned in #48). Here I'm fixing these deprecated types.
=> Remove deprecated numpy types to make things work with numpy 1.24.0

.github/workflows/ci.yml, environment-py37.yml
Currently, the `conda` environment in CI is built through several manual `conda` calls. This seems to be quite slow, especially for Python 3.9, where it can even take 20-60 minutes. This PR switches to using `mamba` through the open-source `conda-incubator/setup-miniconda` action, which makes environment solving much faster (2-3 min) and more predictable.
=> Use conda-incubator/setup-miniconda to setup conda

CHANGELOG.md, molecule_generation/test/integration/test_data_moler_integration.py, molecule_generation/utils/moler_inference_server.py, molecule_generation/wrapper.py
For downstream analysis, it is often useful to be able to look at the entire generation trace of decoded molecules. In this PR, I'm extending the high-level model interface to (optionally) expose this information.
=> Expose generation steps in VaeWrapper

CHANGELOG.md
So far the `CHANGELOG.md` file followed [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), which is somewhat underspecified; this led to inconsistent-looking changelog entries. [Common Changelog](https://common-changelog.org/) is a stricter variant which makes it explicit how the entries should be written. In this PR, I'm switching to the latter, and adjusting existing changelog entries to match that.
=> Adapt the CHANGELOG to the Common Changelog format

CHANGELOG.md, README.md, setup.py
This PR expands on the Tensorflow troubleshooting section in `README.md`, taking into account how installing the newest versions on Ubuntu 22.04 requires extra care (fixes #61). On top of this, I also relaxed the pin on `protobuf` version in `setup.py`; I'm not sure why the lower bound was introduced, but some of the `tensorflow` versions actually conflict with it.
=> Expand README and relax protobuf version requirement

.github/workflows/ci.yml, CHANGELOG.md, environment.yml, molecule_generation/utils/moler_inference_server.py, setup.py
This PR addresses two sources of memory leaks apparent when repeatedly encoding many molecules in a loop, both originating from `tensorflow`:
- First, there is a very mild leak, caused by `tensorflow` not fully cleaning up some of its internals, which appears across many `tensorflow` versions.
- Second, there is also a bigger leak introduced in `tensorflow` vesion `2.10`.
The first issue is addressed by manually clearing `_py_funcs_used_in_graph`, while for the second I temporarily pin the supported `tensorflow` version to `<2.10`, awaiting the issue to be fixed upstream. The pin also avoids backward compatibility problems that start to appear in `2.14` and prevent the pretrained checkpoint from being loaded (see #67).
=> Avoid memory leaks and other tensorflow issues

.github/workflows/ci.yml
The Python 3.7 CI has been problematic for a while now, as the integration tests tend to crash for unclear reasons. Given that this does not appear under 3.8, 3.9 or 3.10, and that 3.7 is now past it's end-of-life, in this PR I drop the 3.7 CI.
=> Stop running CI under Python 3.7

CHANGELOG.md, molecule_generation/layers/moler_decoder.py
When a scaffold is provided during decoding, we assume the model is free to attach further atoms to any atom in the scaffold, unless it contains explicit attachment points, in which case we only allow attaching to those atoms. However, the handling of these attachment points had a bug regarding explicit hydrogens, which would cause the scaffold molecule to be malformed and decoding to fail. This PR fixes this issue by carefully updating the hydrogen count where appropriate.
=> Fix hydrogen handling in scaffolds with explicit attachment points
